import bcrypt from 'bcrypt';

const data = {
    users: [
        {
            name: 'Manishankar Vakta',
            email: 'manishankarvakta@gmail.com',
            password: bcrypt.hashSync('12345', 8),
            type: 'admin',
            status: true
        },
        {
            name: 'Pos User',
            email: 'pos@gmail.com',
            password: bcrypt.hashSync('12345', 8),
            type: 'pos',
            status: true
        },
        {
            name: 'Manager',
            email: 'manager@gmail.com',
            password: bcrypt.hashSync('12345', 8),
            type: 'manager',
            status: true
        }
    ],
    products: [
        {
          "name": "Freshlife Adult Diaper-Medium 8Pcs",
          "ean": "8697512322298",
          "article_code": "5110001",
          "master_category": "Baby Care",
          "category": "Hygiene",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Freshlife-Adult-Diaper-Medium-8Pcs",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Freshmaker Wet Wipes with Fliptop 120Pcs",
          "ean": "8697817871293",
          "article_code": "5110002",
          "master_category": "Baby Care",
          "category": "Hygiene",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Freshmaker-Wet-Wipes-with-Fliptop-120Pcs",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Freshmaker Wet Wipes with Fliptop 72Pcs",
          "ean": "8697817875543",
          "article_code": "5110003",
          "master_category": "Baby Care",
          "category": "Hygiene",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Freshmaker-Wet-Wipes-with-Fliptop-72Pcs",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Smart Care Wet Wipes With Fliptop 120Pcs",
          "ean": "7802013796214",
          "article_code": "5110004",
          "master_category": "Baby Care",
          "category": "Hygiene",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Smart-Care-Wet-Wipes-With-Fliptop-120Pcs",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Smart Care Wet Wipes With Tube 220 Pcs",
          "ean": "764460703481",
          "article_code": "5110005",
          "master_category": "Baby Care",
          "category": "Hygiene",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Smart-Care-Wet-Wipes-With-Tube-220-Pcs",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Smart Care Wet Wipes With Tube 160 Pcs",
          "ean": "764460703474",
          "article_code": "5110006",
          "master_category": "Baby Care",
          "category": "Hygiene",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Smart-Care-Wet-Wipes-With-Tube-160-Pcs",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Smart Care Baby Feeding Bottle -PP(2 OZ)",
          "ean": "0745760115549",
          "article_code": "5110007",
          "master_category": "Baby Care",
          "category": "Baby Accessories",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Smart-Care-Baby-Feeding-Bottle--PP(2-OZ)",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Smart Care Borosilicate Glass Bottle 4 OZ",
          "ean": "0745760115570",
          "article_code": "5110008",
          "master_category": "Baby Care",
          "category": "Baby Accessories",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Smart-Care-Borosilicate-Glass-Bottle-4-OZ",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Smart Care Breast Pump Manual",
          "ean": "0745760115679",
          "article_code": "5110009",
          "master_category": "Baby Care",
          "category": "Baby Accessories",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Smart-Care-Breast-Pump-Manual",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Smart Care Baby thin Cotton bud 100 pcs",
          "ean": "5110010",
          "article_code": "5110010",
          "master_category": "Baby Care",
          "category": "Baby Accessories",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Smart-Care-Baby-thin-Cotton-bud-100-pcs",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Smart Care Baby thin Cotton bud rotate box 180 pcs",
          "ean": "5110011",
          "article_code": "5110011",
          "master_category": "Baby Care",
          "category": "Baby Accessories",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Smart-Care-Baby-thin-Cotton-bud-rotate-box-180-pcs",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Smart Care Baby thin Cotton bud Square box 200 pcs",
          "ean": "5110012",
          "article_code": "5110012",
          "master_category": "Baby Care",
          "category": "Baby Accessories",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Smart-Care-Baby-thin-Cotton-bud-Square-box-200-pcs",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Smart Care Milk Powder Container 4 layers Each",
          "ean": "5110013",
          "article_code": "5110013",
          "master_category": "Baby Care",
          "category": "Baby Accessories",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Smart-Care-Milk-Powder-Container-4-layers-Each",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Smart Care Water Spout Cup 180 ML",
          "ean": "5110014",
          "article_code": "5110014",
          "master_category": "Baby Care",
          "category": "Baby Accessories",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Smart-Care-Water-Spout-Cup-180-ML",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Formula Platinum Sensitive Toothbrush -Active Care Each",
          "ean": "8991102024778",
          "article_code": "5110015",
          "master_category": "Baby Care",
          "category": "Hygiene",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Formula-Platinum-Sensitive-Toothbrush--Active-Care-Each",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Formula Platinum Protector Extreme Clean Toothbrush Each",
          "ean": "8991102023115",
          "article_code": "5110016",
          "master_category": "Baby Care",
          "category": "Hygiene",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Formula-Platinum-Protector-Extreme-Clean-Toothbrush-Each",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Formula Confident Curve Toothbrush Each",
          "ean": "8991102024099",
          "article_code": "5110017",
          "master_category": "Baby Care",
          "category": "Hygiene",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Formula-Confident-Curve-Toothbrush-Each",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Formula Ripple Tooth Brush Each",
          "ean": "8991102022347",
          "article_code": "5110018",
          "master_category": "Baby Care",
          "category": "Hygiene",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Formula-Ripple-Tooth-Brush-Each",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Formula Junior Kiddo Optimum Toothbrush Each",
          "ean": "8991102023955",
          "article_code": "5110019",
          "master_category": "Baby Care",
          "category": "Hygiene",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Formula-Junior-Kiddo-Optimum-Toothbrush-Each",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Creme 21 Cream 50ml",
          "ean": "6294007500210",
          "article_code": "5110020",
          "master_category": "Baby Care",
          "category": "Skin Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Creme-21-Cream-50ml",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Cussons Imperial Leather Classic Soap 115g",
          "ean": "6297000323060",
          "article_code": "5110021",
          "master_category": "Baby Care",
          "category": "Skin Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Cussons-Imperial-Leather-Classic-Soap-115g",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Cussons Imperial Leather Classic Soap 200g",
          "ean": "8850169047024",
          "article_code": "5110022",
          "master_category": "Baby Care",
          "category": "Skin Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Cussons-Imperial-Leather-Classic-Soap-200g",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Huggies Baby Wipes 80pcs",
          "ean": "8888336016511",
          "article_code": "5110023",
          "master_category": "Baby Care",
          "category": "Baby Hygiene",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Huggies-Baby-Wipes-80pcs",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Kodomo Dental Kids Set ( 6+) 1 Set",
          "ean": "8850002804692",
          "article_code": "5110024",
          "master_category": "Baby Care",
          "category": "Baby Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Kodomo-Dental-Kids-Set-(-6+)-1-Set",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Kodomo Dental Kids Set (0.5-3) 1 Set",
          "ean": "8850002804678",
          "article_code": "5110025",
          "master_category": "Baby Care",
          "category": "Baby Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Kodomo-Dental-Kids-Set-(0.5-3)-1-Set",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Kodomo Dental Kids Set (3-6) 1 Set",
          "ean": "8850002804685",
          "article_code": "5110026",
          "master_category": "Baby Care",
          "category": "Baby Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Kodomo-Dental-Kids-Set-(3-6)-1-Set",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Kodomo Tooth Brush 0.5-3 1 Set",
          "ean": "8888300120060",
          "article_code": "5110027",
          "master_category": "Baby Care",
          "category": "Baby Oral Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Kodomo-Tooth-Brush-0.5-3-1-Set",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Kodomo Tooth Brush 6+ 1 Set",
          "ean": "8888300120084",
          "article_code": "5110028",
          "master_category": "Baby Care",
          "category": "Baby Oral Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Kodomo-Tooth-Brush-6+-1-Set",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Kodomo Tooth paste Cream Strawberry 40 GM",
          "ean": "8850002015203",
          "article_code": "5110029",
          "master_category": "Baby Care",
          "category": "Baby Oral Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Kodomo-Tooth-paste-Cream-Strawberry-40-GM",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Kodomo Tooth paste Cream Orange 40 GM",
          "ean": "8850002015227",
          "article_code": "5110030",
          "master_category": "Baby Care",
          "category": "Baby Oral Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Kodomo-Tooth-paste-Cream-Orange-40-GM",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Kodomo Tooth paste Cream Grpape 40 GM",
          "ean": "5110031",
          "article_code": "5110031",
          "master_category": "Baby Care",
          "category": "Baby Oral Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Kodomo-Tooth-paste-Cream-Grpape-40-GM",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Kodomo Tooth paste Gel Strawberry 40 GM",
          "ean": "8850002008670",
          "article_code": "5110032",
          "master_category": "Baby Care",
          "category": "Baby Oral Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Kodomo-Tooth-paste-Gel-Strawberry-40-GM",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Kodomo Tooth paste Gel Bubble Fruit 40 GM",
          "ean": "8850002008663",
          "article_code": "5110033",
          "master_category": "Baby Care",
          "category": "Baby Oral Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Kodomo-Tooth-paste-Gel-Bubble-Fruit-40-GM",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Kodomo Tooth paste Cream Strawberry 80 GM",
          "ean": "8888300800610",
          "article_code": "5110034",
          "master_category": "Baby Care",
          "category": "Baby Oral Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Kodomo-Tooth-paste-Cream-Strawberry-80-GM",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        },
        {
          "name": "Kodomo Tooth paste Cream Orange 80 GM",
          "ean": "8888300800627",
          "article_code": "5110035",
          "master_category": "Baby Care",
          "category": "Baby Oral Care",
          "product_type": "standard",
          "brand": "no-brand",
          "unit": "EA",
          "sale_unit": "EA",
          "purchase_unit": "EA",
          "alert_quantity": 12,
          "vat": "5",
          "vat_method": "in",
          "shipping_method": "cod",
          "slug": "Kodomo-Tooth-paste-Cream-Orange-80-GM",
          "featured": false,
          "hide_website": false,
          "photo": "photo.jpg",
          "status": true
        }
      ]
}



export default data;